### PR TITLE
Fix codegen signed long-double issue, fixes #233

### LINKED ISSUE #233: Invalid codegen output for LiteralNumericExpressions > 2^63.
Any integer over `2^63` is output as `0x7FFFFFFFFFFFFFFF`, which is incorrect.

### PR DESCRIPTION
**Pull request by Protryon**
Fixes #233.

### CODE REVIEW

File: src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java [hunk 1]
```diff
@@ -159,7 +159,7 @@ public static String shortD2a(double n) {
             }
             return "0"; // Not reached
         } else if (n % 1 == 0) {
-            if (n > 1e15 && n < 1e20) {
+            if (n > 1e15 && n < 2.3e18) {
```
Comment (michaelficarra) [inline src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java]: Why this number?

```
λ> 2 ^ 63
9223372036854775808
λ> 23 * (10 ^ 17)
2300000000000000000
```

File: src/test/java/com/shapesecurity/shift/es2017/codegen/CodeGenTest.java [hunk 2]
```diff
@@ -587,6 +587,8 @@ public void testLiteralNumericExpression() throws JsError {
         test("1e308", "1e+308");
         test("1e308");
         test("1e-308");
+        test("9223372036854775807");
```
Comment (michaelficarra) [inline src/test/java/com/shapesecurity/shift/es2017/codegen/CodeGenTest.java:590]:
```
$ node
> 9223372036854775807 < 9223372036854775808
false
```

You should choose another double that's actually smaller than `2 ** 63` to test this. I believe this would just work even without your fix. `9223372036854775295` seems to be the largest double that's smaller than `2 ** 63`.

File: src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java [hunk 3]
```diff
@@ -159,7 +159,7 @@ public static String shortD2a(double n) {
             }
             return "0"; // Not reached
         } else if (n % 1 == 0) {
-            if (n > 1e15 && n < 1e20) {
+            if (n > 1e15 && n < Math.pow(2, 63)) {
```
Comment (michaelficarra) [inline src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java]: It looks like the lower bound is looser than it needs to be, too.

```java
if (n >= 1e12 && n < 0x8000000000000000 /* 2^63 */) {
```

Comment (Protryon) [reply src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java]: This is java, we cannot represent an integer >= 2^63 `0x8000000000000000`, hence the usage of a double. I will change the lower bound.

Comment (michaelficarra) [reply src/main/java/com/shapesecurity/shift/es2017/utils/D2A.java]: Ugh I assumed it would treat it as a double. Either way, works for me.

**Review by michaelficarra — APPROVED** [review]
