### PR TITLE
Fix escaped keywords, Fixes #220

### LINKED ISSUE #220: Contextual Keyword Escapes
Currently we accept contextual keywords with escapes in them, this is not to spec.

### PR DESCRIPTION
**Pull request by Protryon**
Fixed issue #220.

### CODE REVIEW

File: src/main/java/com/shapesecurity/shift/es2017/parser/GenericParser.java [hunk 1]
```diff
@@ -74,7 +71,11 @@ protected boolean match(@Nonnull TokenType subType) {
 
     protected boolean matchIdentifier() {
         switch(this.lookahead.type) {
-            case IDENTIFIER:
+			case ESCAPED_KEYWORD:
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/GenericParser.java]: whitespace

Comment (bakkot) [reply src/main/java/com/shapesecurity/shift/es2017/parser/GenericParser.java]: Also elsewhere; not going to comment on all of them.

File: src/main/java/com/shapesecurity/shift/es2017/parser/token/EscapedKeywordToken.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+package com.shapesecurity.shift.es2017.parser.token;
+
+import com.shapesecurity.shift.es2017.parser.SourceRange;
+import com.shapesecurity.shift.es2017.parser.TokenType;
+
+import javax.annotation.Nonnull;
+
+public class EscapedKeywordToken extends IdentifierToken {
+
+    public EscapedKeywordToken(@Nonnull SourceRange slice, @Nonnull CharSequence name, boolean escaped) {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/token/EscapedKeywordToken.java]: Why does this take an `escaped` parameter? Surely an `EscapedKeywordToken` is always escaped?

File: src/main/java/com/shapesecurity/shift/es2017/parser/GenericParser.java [hunk 3]
```diff
@@ -414,15 +420,17 @@ protected BindingIdentifier parseBindingIdentifier() throws JsError {
     @Nonnull
     protected String parseIdentifier() throws JsError {
         if (this.matchIdentifier()) {
-            if (this.match(TokenType.YIELD) && this.allowYieldExpression) {
+			String value = this.lookahead.toString();
+			if (this.match(TokenType.YIELD) && this.allowYieldExpression || this.allowYieldExpression && this.match(TokenType.ESCAPED_KEYWORD) && value.equals("yield") && ((IdentifierToken) this.lookahead).escaped) {
                 throw this.createError(ErrorMessages.INVALID_TOKEN_CONTEXT, "yield");
-            } else if (this.match(TokenType.AWAIT) && (this.allowAwaitExpression || this.moduleIsTheGoalSymbol)) {
+            } else if ((this.allowAwaitExpression || this.moduleIsTheGoalSymbol) && (this.match(TokenType.AWAIT) || this.match(TokenType.ESCAPED_KEYWORD) && value.equals("await") && ((IdentifierToken) this.lookahead).escaped )) {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/GenericParser.java]: Why is the last condition necessary? Is it ever false, given the earlier `this.match(TokenType.ESCAPED_KEYWORD)`?

File: src/main/java/com/shapesecurity/shift/es2017/parser/token/EscapedKeywordToken.java [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+ */
+
+package com.shapesecurity.shift.es2017.parser.token;
+
+import com.shapesecurity.shift.es2017.parser.SourceRange;
+import com.shapesecurity.shift.es2017.parser.TokenType;
+
+import javax.annotation.Nonnull;
+
+public class EscapedKeywordToken extends IdentifierToken {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/token/EscapedKeywordToken.java]: I don't think it's a good idea for this to subclass `IdentifierToken`. We treat these tokens as being effectively `enum`s, not classes with inheritance.

File: src/test/java/com/shapesecurity/shift/es2017/test262/expectations/XFailHelper.java [hunk 5]
```diff
@@ -110,7 +110,6 @@
 				"language/literals/string/legacy-non-octal-escape-sequence-strict.js"
 		));
 		xfailFiles.addAll(Arrays.asList(Regexp.xfail));
-		xfailFiles.addAll(Arrays.asList(ContextualKeywordEscapes.xfail));
```
Comment (bakkot) [inline src/test/java/com/shapesecurity/shift/es2017/test262/expectations/XFailHelper.java:113]: Presumably `ContextualKeywordEscapes.java` should also be deleted, yes?

**Comment by Protryon** [comment]
@bakkot Ready for review.

**Comment by bakkot** [comment]
Failing CI. Also, is there a reason this is `ESCAPED_IDENTIFIER` instead of `ESCAPED_KEYWORD`? I'd prefer to match the JS implementation unless there's a strong reason not to.

File: src/main/java/com/shapesecurity/shift/es2017/parser/TokenType.java [hunk 6]
```diff
@@ -107,6 +107,7 @@
     STRING(TokenClass.StringLiteral, "string"),
     REGEXP(TokenClass.RegularExpression, "regexp"),
     IDENTIFIER(TokenClass.Ident, "identifier"),
+    ESCAPED_KEYWORD(TokenClass.Ident, "escaped-keyword"),
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/TokenType.java]: Feel a little weird about this being `Ident` instead of `Keyword`. (shift-parser-js has [`Keyword`](https://github.com/shapesecurity/shift-parser-js/blob/f973b067adbb7e72fe3a010596bc50c73a5e6f3c/src/tokenizer.js#L132).) Is there a reason for it? I don't think it affects much either way; I'd prefer to default to matching the JS implementation unless there's a reason not to. Or we could change it, if there's a strong argument for `Ident` being correct.

File: src/main/java/com/shapesecurity/shift/es2017/parser/Tokenizer.java [hunk 7]
```diff
@@ -699,31 +692,42 @@ private CharSequence getIdentifier() throws JsError {
...
+        }
 
         SourceRange slice = this.getSlice(start);
 
         TokenType subType = this.getKeyword(id);
         if (subType == TokenType.IDENTIFIER) {
-            return new IdentifierToken(slice, id);
+            return new IdentifierToken(subType, slice, id, escaped);
+        } else if (escaped) {
+            return new IdentifierToken(TokenType.ESCAPED_KEYWORD, slice, id, true);
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/shift/es2017/parser/Tokenizer.java]: Ditto above comment, actually - why is this an `IdentifierToken` instead of a `KeywordToken` with subtype `ESCAPED_KEYWORD`? If it were a `KeywordToken`, then the `IdentifierToken` constructor would not need the new parameter(s).

Comment (Protryon) [reply src/main/java/com/shapesecurity/shift/es2017/parser/Tokenizer.java]: The new parameter is used for escaped identifiers (used for contextual keywords), while `ESCAPED_KEYWORD` is used for known keywords that are escaped, so the parameter will still be needed. I can change it to a KeywordToken with some other changes.

**Review by bakkot — APPROVED** [review]
